websocio/comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
    path('add_comment/', views.add_comment, name='add_comment'),
]

websocio/images/urls.py
from django.urls import path
from . import views


app_name = "images"


urlpatterns = [
    path('<int:page>/', views.images, name="images"),
    path('add/', views.add_image, name="add"),
    path('detail/<int:id>/<slug:slug>/', views.detail, name="detail"),
    path('image_like/', views.image_like, name='image_like'),
    path('ranking/', views.image_ranking, name='ranking'),
]

websocio/main/urls.py
from django.urls import path
from . import views
import django.contrib.auth.views as auth_views


urlpatterns = [
    path('', views.dashboard, name="main"),
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('change_password/', auth_views.PasswordChangeView.as_view(), name="change_password"),
    path('change_password/done', auth_views.PasswordChangeDoneView.as_view(), name="change_password_done"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('edit/', views.edit, name="edit"),

]

websocio/people/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'people'


urlpatterns = [
    path('<int:page>/', views.people, name='people'),
    path('user_detail/<int:id>/', views.user_detail, name='user_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocio/websocio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),
    path('images/', include("images.urls")),
    path('people/', include("people.urls")),
    path('comments/', include('comments.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocio/images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.


class Image(models.Model):
    url = models.URLField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="created_image", on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    image = models.ImageField(upload_to="images/%Y/%m/%d")
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="images_liked", blank=True)
    total_likes = models.PositiveIntegerField(blank=True, default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])

websocio/images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ("title", "url", "description")

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = url.rsplit(".", 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("The given URL does not match valid image extensions")
        return url

    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit(".", 1)[1].lower())
        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)
        if commit:
            image.save()
        return image

websocio/images/views.py
import redis
from django.shortcuts import render, get_object_or_404
from .forms import ImageForm
from django.contrib import messages
from .models import Image
from django.http import JsonResponse, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
from django.contrib.auth.decorators import login_required
from comments.forms import CommentForm
from comments.models import Comment


# Create your views here.
r = redis.Redis(host="localhost", port=6379, db=0)


@login_required
def add_image(request):
    if request.method == "POST":
        image_form = ImageForm(request.POST)
        if image_form.is_valid():
            image_save = image_form.save(commit=False)
            image_save.user = request.user
            image_save.save()
            messages.success(request, "Image saved successfully!")
            create_action(request.user, "added image", image_save)
        else:
            messages.error(request, "Image save error")
    else:
        image_form = ImageForm()
    return render(request, "images/add.html", {'image_form': image_form})


@login_required
def detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr("image:{}:views".format(image.id))
    r.zincrby("image_ranking", image.id, 1)
    comments = Comment.objects.filter(image_id=image.id)
    comment_form = CommentForm()
    return render(request, 'images/detail.html', {'image': image, 'total_views': total_views,
                                                  'comment_form': comment_form, 'comments': comments})


@login_required
def image_like(request):
    image_id = request.POST.get('id')
    image_action = request.POST.get('action')
    print(image_id, image_action)
    if image_id and image_action:
        try:
            image = Image.objects.get(id=image_id)
            if image_action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, "likes", image)
            else:
                image.users_like.remove(request.user)
        except Exception:
            return JsonResponse({'status': 'error'})
    return JsonResponse({'status': 'ok'})


@login_required
def images(request, page):
    images = Image.objects.all()
    paginator = Paginator(images, 2)
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
    if request.is_ajax():
        return render(request, "images/images_ajax.html", {"images": images})
    return render(request, "images/images.html", {"images": images})


@login_required
def image_ranking(request):
    # Получаем набор рейтинга картинок.
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    print(image_ranking)
    image_ranking_ids = [int(id) for id in image_ranking]
    # Получаем отсортированный список самых популярных картинок.
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    print(most_viewed)
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,
                 'images/ranking.html',
                 {'section': 'images',
                 'images': most_viewed})

websocio/images/templates/images/add.html
{% extends 'base.html' %}

{% block title %}
    Add image
{% endblock %}

{% block content %}
    <h1>Add image</h1>
    <p>You can add image using the following form. After that other users will be able to see it, and notice it. </p>
    <form action="." method="POST">
        {{image_form.as_p}}
        {% csrf_token %}
        <input type="submit" value="Add">
    </form>
{% endblock %}

websocio/images/templates/images/detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
    {{image.title}}
{% endblock %}

{% block content %}
    <h1>{{image.title}}</h1>
    {% thumbnail image.image "800" as im %}
    <a href="{{image.image.url}}">
        <img src="{{im.url}}">
        </a>
    {% endthumbnail %}
    <p>{{image.description}}</p>
{% with users_like=image.users_like.all  count=image.users_like.count%}
<span>{{total_views}} views</span><br>
<span ><span class="count">{{count}}</span> likes</span>
    <a href="#"  data-id="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like">
        {% if request.user in users_like %}
        Unlike
        {% else %}
        Like
        {% endif %}
    </a>
<br><br><span>Added by <a href="{% url 'people:user_detail' image.user.id %}">{{image.user.username}}</a></span>
<div class="comments"> {% include 'comments/comments_ajax.html' %}</div>
<div class="comment_form">
    <textarea cols="5" style="width:100%" id="comment_text"></textarea>
    <a href="#" class="comment_btn" data-id="{{image.id}}">Отправить</a>
</div>
{% endwith %}
{% endblock %}

{% block domready %}
    $('a.comment_btn').click(function(e){
      e.preventDefault();

      if($('#comment_text').val() != '')(
      $.post("{% url 'comments:add_comment' %}",
          {id: $('a.comment_btn').data('id'),
          text: $('#comment_text').val()},
          function(data) {
            $('#comment_text').val('');
          $('div.comments').append(data);
          }
      ));
    });



    $('a.like').click(function(e) {
    e.preventDefault();
    $.post("{% url 'images:image_like' %}",
            {id: $(this).data('id'),
            action: $(this).data('action')},
            function(data) {
                if (data['status'] == 'ok') {
                    let previous_action = $('a.like').data('action');
                    console.log(previous_action);
                    $('a.like').data('action', previous_action == 'like'? 'unlike': 'like');
                    $('a.like').text(previous_action == 'like'? 'Unlike': 'Like')
                    $('span.count').text(previous_action == 'like'? parseInt($('span.count').text()) + 1: parseInt($('span.count').text()) - 1)
                }
            })
    })
{% endblock %}

websocio/images/templates/images/images.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    Images
{% endblock %}

{% block content %}
<h1>Images</h1>
<p>ON this page you can see al pictures on our site. Also you can <a href="{% url 'images:add'%}">add image</a></p>
<p>Also you can check most popular images<a href="{% url 'images:ranking' %}"> here</a></p>
<div id="image_list">
    {% include "images/images_ajax.html" %}
    </div>
{% endblock %}

{% block domready %}
        var page = 1;
        let empty_page = false;
        $(window).scroll(function(){
          if(document.documentElement.getBoundingClientRect().bottom < document.documentElement.clientHeight + 100 && !empty_page) {
            page +=1;
            $.get("{% url 'images:images' page=12345 %}".replace(/12345/, page.toString()), function(data) {
                    if(data == '') {empty_page = true;}
                    else{
                       $("#image_list").append(data);
                    }
                });
            }
        });

{% endblock %}

websocio/images/templates/images/images_ajax.html
{% load thumbnail %}
{% for image in images %}
<a href="{{image.get_absolute_url}}">
{% thumbnail image.image "500x500" as im %}
    <div class="image-block">
        <span class="image_name">{{image.title}}</span><br>
    <img src="{{im.url}}">
        </div>

{% endthumbnail %}
    </a>
{% endfor %}

websocio/images/templates/images/ranking.html
{% extends 'base.html' %}

<p>Here is most popular images on our site.</p>
<br><br>
<ol>
{% for image in images %}
    <li>
        <a href="{{image.get_absolute_url}}">{{image.title}}</a>
    </li>
{% endfor %}
    </ol>