websocio/images/urls.py
from django.urls import path
from . import views


app_name = "images"


urlpatterns = [
    path('<int:page>/', views.images, name="images"),
    path('add/', views.add_image, name="add"),
    path('detail/<int:id>/<slug:slug>/', views.detail, name="detail"),
    path('image_like/', views.image_like, name='image_like'),
    path('ranking/', views.image_ranking, name='ranking'),
]

websocio/main/urls.py
from django.urls import path
from . import views
import django.contrib.auth.views as auth_views


urlpatterns = [
    path('', views.dashboard, name="main"),
    path('register/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('change_password/', auth_views.PasswordChangeView.as_view(), name="change_password"),
    path('change_password/done', auth_views.PasswordChangeDoneView.as_view(), name="change_password_done"),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('edit/', views.edit, name="edit"),

]

websocio/people/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'people'


urlpatterns = [
    path('<int:page>/', views.people, name='people'),
    path('user_detail/<int:id>/', views.user_detail, name='user_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocio/websocio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),
    path('images/', include("images.urls")),
    path('people/', include("people.urls")),
    path('comments/', include('comments.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

websocio/main/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_birth = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to="images/%Y/%m/%d/", blank=True)


class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='user_from', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='user_to', on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ('-created',)


User.add_to_class("following", models.ManyToManyField('self', through=Contact, related_name="followers",
                                                      symmetrical=False))

websocio/main/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.PasswordInput()


class RegistrationForm(forms.ModelForm):
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username", "first_name", "email")

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Passwords don't match")
        return cd['password2']


class UserEdit(forms.ModelForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")


class ProfileEdit(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_birth', 'photo')

websocio/main/views.py
from django.shortcuts import render
from . forms import RegistrationForm, ProfileEdit, UserEdit
from .models import Profile, Contact
from django.contrib import messages
from actions.models import Action
from django.contrib.auth.decorators import login_required

# Create your views here.


@login_required
def dashboard(request):
    actions = Action.objects.exclude(user=request.user)
    following_ids = request.user.following.values_list('id', flat=True)
    if following_ids:
        actions = actions.filter(user_id__in=following_ids)
    actions = actions.select_related('user', 'user__profile').prefetch_related('target')[:10]
    return render(request, 'main/dashboard.html', {'actions': actions})


def register(request):
    if request.method == "POST":
        register_form = RegistrationForm(request.POST)
        if register_form.is_valid():
            new_user = register_form.save(commit=False)
            new_user.set_password(register_form.cleaned_data['password1'])
            new_user.save()
            Profile.objects.create(user=new_user).save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})
    else:

        register_form = RegistrationForm()
    return render(request, 'registration/register.html', {'register_form': register_form})


@login_required
def edit(request):
    if request.method == "POST":
        user_form = UserEdit(data=request.POST, instance=request.user)
        profile_form = ProfileEdit(data=request.POST, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile update successfully")
        else:
            messages.error(request, "Profile update error")
    else:
        profile_form = ProfileEdit(instance=request.user.profile)
        user_form = UserEdit(instance=request.user)
    return render(request, "main/edit.html", {"user_form": user_form, "profile_form": profile_form})

websocio/main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>

<header class="container-fluid">
<div class="container hmenu">
    <div class="row">
        <div class="col-6">
    <span class="logo">SOcio-club</span>
            </div>
        <div style="text-align: right" class="col-6">
    <span class="user" style="text-align: right">
        {% if request.user.is_authenticated  %}
        Hello, {{ request.user.first_name }}
        <a href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a><br>
        <a href="{% url 'register' %}">Registration</a>
        {% endif %}
    </span>
            </div>
        </div>
    <ul>
        <li class="menu"><a href="{% url 'main' %}">My dashboard</a></li>
         <li class="menu"><a href="{% url 'images:add' %}">Add images</a></li>
         <li class="menu"><a href="{% url 'images:images' 1 %}">Images</a></li>
         <li class="menu"><a href="{% url 'people:people' 1 %}">People</a></li>
    </ul>
</div>
</header>
<div class="container">
{% block content %}
{% endblock %}
</div>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{message.tags}}">
                {{ message|safe }}
                <a href="#" class="close">x</a>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
<script>
 let csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({beforeSend: function(xhr, settings){
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken)
        }
        }
    });
    $(document).ready(function(){
        {% block domready %}
        {% endblock %}
    });
    </script>
</body>
</html>